# Generated by Django 5.2.12 on 2026-04-22 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_recurringdonation_payment_status'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='donations.donation'),
        ),
    ]
