# Generated by Django 5.2.12 on 2026-05-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_billing_recurring_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
