# Generated by Django 5.2.12 on 2026-05-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_alter_billing_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='pdf_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
