# Generated by Django 5.2.12 on 2026-05-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_billing_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='pdf_file',
        ),
    ]
