# Generated by Django 5.2.12 on 2026-04-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_recurringdonation_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='recurring',
        ),
    ]
