# Generated by Django 5.2.12 on 2026-04-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_remove_donation_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringdonation',
            name='last_payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
