# Generated by Django 5.2.12 on 2026-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_recurringdonation_last_payment_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringdonation',
            old_name='last_payment_at',
            new_name='last_donated_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='SUCCESS', max_length=15),
        ),
    ]
