# Generated by Django 5.2.12 on 2026-04-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_rename_last_payment_at_recurringdonation_last_donated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringdonation',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='SUCCESS', max_length=10),
        ),
    ]
