# Generated by Django 5.2.12 on 2026-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_recurringdonation_is_processing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringdonation',
            old_name='last_donated_at',
            new_name='last_run',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('NPR', 'Npr'), ('INR', 'Inr')], max_length=5),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('NPR', 'Npr'), ('INR', 'Inr')], max_length=5),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='recurring_timing',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10),
        ),
    ]
