# Generated by Django 5.2.12 on 2026-04-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_rename_last_donated_at_recurringdonation_last_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringdonation',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=10),
        ),
    ]
