# Generated by Django 5.2.12 on 2026-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_recurringdonation_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringdonation',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
