# Generated by Django 5.2.12 on 2026-04-23 02:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_alter_recurringdonation_next_run'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringdonation',
            old_name='payment_status',
            new_name='last_payment_status',
        ),
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
