# Generated by Django 5.2.12 on 2026-04-23 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('donations', '0010_rename_payment_status_recurringdonation_last_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='RecurringDonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'Usd'), ('NPR', 'Npr'), ('INR', 'Inr')], max_length=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=10)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='campaign.campaign')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recurring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='donations.recurringdonation')),
            ],
        ),
    ]
