# Generated by Django 5.2.12 on 2026-04-23 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_remove_donation_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringdonationhistory',
            old_name='run_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='recurringdonationhistory',
            old_name='recurring',
            new_name='recurring_donation',
        ),
        migrations.RemoveField(
            model_name='recurringdonationhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recurringdonationhistory',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringdonationhistory',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='SUCCESS', max_length=10),
        ),
    ]
