# Generated by Django 5.2.12 on 2026-04-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_rename_run_at_recurringdonationhistory_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringdonationhistory',
            name='created_at',
        ),
    ]
