# Generated by Django 5.2.12 on 2026-05-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_remove_recurringdonationhistory_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recurringdonationhistory',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=10),
        ),
    ]
